# Generated by Django 2.2.12 on 2020-08-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_ewsmaintable_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewsmaintable',
            name='line',
            field=models.CharField(max_length=10, null=True, verbose_name='线号'),
        ),
        migrations.AlterField(
            model_name='ewsmaintable',
            name='modelName',
            field=models.CharField(max_length=30, null=True, verbose_name='服务码'),
        ),
        migrations.AlterField(
            model_name='ewsmaintable',
            name='number',
            field=models.CharField(max_length=10, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='ewsmaintable',
            name='row',
            field=models.CharField(max_length=10, null=True, verbose_name='杠号'),
        ),
    ]
