# Generated by Django 3.1 on 2020-08-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20200810_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewsmaintable',
            name='modelName',
            field=models.CharField(max_length=30, null=True, verbose_name='型号'),
        ),
    ]
