# Generated by Django 3.1 on 2020-08-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20200818_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWSModelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=30, null=True, verbose_name='型号')),
                ('duration', models.DateTimeField(verbose_name='测试时长')),
            ],
            options={
                'verbose_name_plural': '机型配置信息',
                'db_table': 'ModelInfo',
            },
        ),
    ]
