# Generated by Django 3.1 on 2020-08-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_ewsmodelinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewsmodelinfo',
            name='duration',
            field=models.TimeField(verbose_name='测试时长'),
        ),
    ]
