version: "3"
services:
        ews:
                restart: always
                build: .  # '点'代表当前目录
                command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
                volumes:
                        - .:/code
                ports:
                        - "8000:8000"
                depends_on:
                        - "ews_db"
        ews_db:
                image: mysql:5.7
                volumes:
                        - "./mysql:/var/lib/mysql"
                ports:
                        - "3306:3306"
                restart: always
                environment:
                        - MYSQL_ROOT_PASSWORD=123456
                        - MYSQL_DATABASE=EWS
           
